packages:
  - "packages/*"
allowBuilds:
  '@google/genai': false
  koffi: false
  protobufjs: false
autoInstallPeers: false
overrides:
  pi-interactive-subagent: 'github:davidsunglee/pi-interactive-subagent#v4.0.0'
